language: python
python:
  - "3.6"
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu
install:
  - "pip install pytest"
  - "pip install -r requirements.txt"
  - "pip install selenium"
  - "pip install -U behave"
script: python -m behave tests/acceptance