language: python
python:
  - "3.6"
install:
  - "pip install pytest"
  - "pip install -r requirements.txt"
  - "pip install selenium"
  - "pip install webdriver-manager"
  - "pip install -U behave"
script:
  - python app.py && python -m behave tests/acceptance
