language: python
python:
  - "3.6"
  - "nightly"
install:
  - "pip install pytest"
  - "pip install -r requirements.txt"
  - "pip install selenium"
  - "pip install webdriver_manager"
  - "pip install behave"
script: python -m behave tests/acceptance